### ISSUE TITLE
Slash char "/" in the name

### ISSUE THREAD

**Issue by Barlafuss** [prahladyeri/fixnames#2]
Slash character "/" in the name is not substituted/removed. How to add it?
(Linux Buster)

**Comment by prahladyeri** [comment]
Seems like a trick question! Its pretty much impossible to create a file or a folder with forward slash ("/") even on a linux OS. I just tried to create and couldn't!

    prahlad@ubuntu:~$ touch "tt/t.txt"
    touch: cannot touch 'tt/t.txt': No such file or directory
